# Generated by Django 5.0.7 on 2024-08-04 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0002_rename_timestamp_transaction_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='failed',
            field=models.BooleanField(null=True),
        ),
    ]
