# Generated by Django 5.0.7 on 2024-08-04 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0003_transaction_failed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='failed',
        ),
        migrations.AddField(
            model_name='transaction',
            name='transaction_failed',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
