# Generated by Django 5.0.7 on 2024-08-04 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0004_remove_transaction_failed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_failed',
            field=models.BooleanField(default=False),
        ),
    ]
