# Generated by Django 5.0.7 on 2024-08-05 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0006_remove_transaction_transaction_failed_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='transaction_ok',
            new_name='transaction_valid',
        ),
    ]
